apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: CLUSTER_NAME
spec:
  api:
    loadBalancer:
      class: Network
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://312-k8s-kops-state-ACCOUNT/CLUSTER_NAME
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1c
      name: a
      volumeType: gp3
      volumeSize: 2
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1c
      name: a
      volumeType: gp3
      volumeSize: 2
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
    useServiceAccountExternalPermissions: true
  kubeProxy:
    enabled: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: CLUSTER_VERSION
  masterPublicName: api.CLUSTER_NAME
  networkCIDR: 172.20.0.0/16
  networking:
    cilium:
      enableNodePort: true
  nonMasqueradeCIDR: 100.64.0.0/10
  serviceAccountIssuerDiscovery:
    discoveryStore: s3://312-k8s-kops-oidc-store-ACCOUNT/CLUSTER_NAME/discovery/CLUSTER_NAME
    enableAWSOIDCProvider: true
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-1c
    type: Public
    zone: us-east-1c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: CLUSTER_NAME
  name: master-us-east-1c
spec:
  instanceMetadata:
    httpPutResponseHopLimit: 7
    httpTokens: optional
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  maxPrice: "0.0418"   # to use on-demand instead, just comment out this line
  role: Master
  rootVolumeSize: 15
  subnets:
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: CLUSTER_NAME
  name: nodes-us-east-1c
spec:
  instanceMetadata:
    httpPutResponseHopLimit: 7
    httpTokens: optional
  machineType: t3.medium
  maxPrice: "0.0418"   # to use on-demand instead, just comment out this line
  maxSize: 2
  minSize: 2
  role: Node
  rootVolumeSize: 15
  subnets:
  - us-east-1c
