apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: service1
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
---

apiVersion: v1
kind: Pod
metadata:
  name: httpd
  labels:
    app: service1
spec:
  containers:
  - name: httpd
    image: httpd
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: service1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
  - name: alpine
    image: alpine
    command: ["sleep", "3600"]
