apiVersion: v1
kind: Pod
metadata:
  name: alpine-env
spec:
  containers:
  - name: alpine
    image: alpine
    command: ["sleep", "3000"]
    env:
    - name: user
      valueFrom:
        secretKeyRef:
          name: credentials
          key: user_name
    - name: password
      valueFrom:
        secretKeyRef:
          name: credentials
          key: login_password
    - name: database_add
      valueFrom:
        secretKeyRef:
          name: credentials
          key: database_add

---
apiVersion: v1
kind: Secret
metadata:
  name: credentials
data:
  user_name: "cm9vdCBhZG1pbgo="
  login_password: "MTIzNDUK"
  database_add: "bXlzcWxfc3ZjLmRldi5zdmMK"